user:
  email:
    max_length: 255
  password:
    min_length: 6
  gravatar_size: 80
  per_page: 21
session:
  remember_me?: "1"
micropost:
  content_max_length: 250
  per_page: 10
  image_max_size: 500
